name: chirpstack-iotbo

# networks:
#   default:
#     external:
#       name: net_interface

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      # - ./configuration/cert:/etc/certs:ro
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - "8080:8080"
    networks:
      - net_interface
    user: "1000:1000"  # Match the host's ubuntu user UID:GID (run `id ubuntu` to confirm)
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  # chirpstack-gateway-bridge:
  #   image: chirpstack/chirpstack-gateway-bridge:4
  #   restart: unless-stopped
  #   ports:
  #     - "1700:1700/udp"
  #   volumes:
  #     - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
  #   environment:
  #     - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
  #     - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
  #     - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
  #   depends_on:
  #     - mosquitto
  
  # chirpstack-gateway-bridge-basicstation:
  #   image: chirpstack/chirpstack-gateway-bridge:4
  #   restart: unless-stopped
  #   command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
  #   depends_on:
  #     - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - "8090:8090"
    depends_on:
      - chirpstack
    networks:
      - net_interface

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - /mnt/data/chirpstack/postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack
    networks:
      - net_interface

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - /mnt/data/chirpstack/redisdata:/data
    networks:
      - net_interface

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      # - "8083:8083"
    volumes: 
      - ./configuration/mosquitto/config/:/mosquitto/config/
      # - ./configuration/cert:/etc/certs:ro
    networks:
      - net_interface

# volumes:
#   postgresqldata:
#   redisdata:


networks:
  net_interface:
    external: true